# Generated by Django 6.0.6 on 2026-08-13 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('size_hectares', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('land_use', models.CharField(blank=True, max_length=100, null=True)),
                ('distance_to_ocean_km', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nearby_locations', models.TextField(blank=True, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=200, null=True)),
                ('owner_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('owner_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('owner_address', models.TextField(blank=True, null=True)),
                ('zipa_phone', models.CharField(default='+255 24 223 3026', max_length=50)),
                ('zipa_email', models.EmailField(default='info@zipa.go.tz', max_length=254)),
                ('zipa_address', models.TextField(default='Mazizini, Zanzibar')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_locations', to='api.district')),
            ],
            options={
                'db_table': 'investment_locations',
            },
        ),
    ]
