# Generated by Django 6.0.6 on 2026-08-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_investmentlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentlocation',
            name='investment_type',
            field=models.CharField(choices=[('Tourism', 'Tourism & Hospitality'), ('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Fishing', 'Fishing'), ('Agriculture', 'Agriculture'), ('Industrial', 'Industrial')], default='Tourism', max_length=50),
        ),
    ]
