# Generated by Django 6.0.6 on 2026-08-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_investmentlocation_investment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentlocation',
            name='price_negotiable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='investmentlocation',
            name='price_per_hectare',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
