# Generated by Django 6.0.6 on 2026-08-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_investmentlocation_price_negotiable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_investment_officer',
            field=models.BooleanField(default=False),
        ),
    ]
